FROM node:24.5.0-slim

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/vane

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

EXPOSE 3000

CMD ["yarn", "dev", "--turbopack"]
